import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const space = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "My Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${space.className} bg-slate-50 dark:bg-slate-800`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
